version: '3.8'
services:
  turtlely-app:
    image: sy0215/turtlely-app:latest
    container_name: turtlely-container
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}