version: '3.8'
services:
  turtly-app:
    image: ${DOCKERHUB_USERNAME}/turtly-app:latest
    container_name: turtly-container
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}