spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 구글 OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: 1800 # 30분
  refresh-token-validity-in-seconds: 1209600 # 14일

# Coolsms 설정
coolsms:
  api:
    key: ${COOLSMS_API_KEY}
    secret: ${COOLSMS_API_SECRET}
  from: ${COOLSMS_FROM_NUMBER}
